name: 'Setup custom node and yarn versions'

on:
  push

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Check versions before setup
        run: |
          Before setup - node version: (node --version)
          Before setup - yarn version: $(yarn --version)
          Before setup - yarn location: $(which yarn)

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup yarn
        env:
          YARN_VERSION: '3.2.0'
        run: |
          corepack enable
          corepack prepare "yarn@${YARN_VERSION}" --activate

      - name: Check versions after setup
        run: |
          After setup - node version: (node --version)
          After setup - yarn version: $(yarn --version)
          After setup - yarn location: $(which yarn)
