name: 'Setup custom node and yarn versions'

on:
  push

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Check versions before setup
        run: |
          echo "Before setup - node version: $(node --version)"
          echo "Before setup - yarn version: $(yarn --version)"
          echo "Before setup - yarn location: $(which yarn)"
          echo "Before setup - yarn real location: $(readlink -f $(which yarn))"
          echo "Before setup - yarn cache dir: $(yarn config get cacheFolder)"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup yarn
        env:
          YARN_VERSION: '3.2.0'
        run: |
          corepack enable
          corepack prepare "yarn@${YARN_VERSION}" --activate

      - name: Check versions after setup
        run: |
          echo "After setup - node version: $(node --version)"
          echo "After setup - yarn version: $(yarn --version)"
          echo "After setup - yarn location: $(which yarn)"
          echo "After setup - yarn real location: $(readlink -f $(which yarn))"
          echo "After setup - yarn cache dir: $(yarn config get cacheFolder)"
